const siteData={
 hero:{eyebrow:'Senior Product Manager · 9+ years',title:'I build products from <em>ambiguous problems</em> to measurable outcomes.',lede:'Product, growth, data and AI across fintech, marketplaces and consumer products. 5+ years in Product Management, with hands-on 0→1 building.'},
 impact:[['9+','years experience'],['5+','years in product'],['100K+','app downloads'],['₹8 Cr','monthly business scaled'],['60%','TAT reduction']],
 projects:[
 {id:'01',tag:'0→1 · Fintech',name:'Kuhoo',title:'Building a digital lending ecosystem from 0→1.',copy:'As the first PM, I shaped the student experience and the internal operating system behind it — connecting application, document collection, decisioning, operations and lender workflows into one system.',type:'kuhoo',metrics:[['100K+','downloads'],['₹8 Cr/mo','business scaled'],['60%','sanction TAT ↓'],['90%','onboarding time ↓']]},
 {id:'02',tag:'Growth · Monetization',name:'WorkIndia',title:'Turning existing-user growth into revenue.',copy:'Focused on monetization and retention levers across the existing-user base, using cohort analysis, experimentation and communication economics to improve the business without relying only on acquisition.',type:'workindia',metrics:[['2×','existing-user revenue'],['₹1.5 Cr/mo','monthly revenue'],['30%','first-month cohort ↑'],['25%','communication cost ↓']]},
 {id:'03',tag:'Marketplace · Scale',name:'Ola',title:'Products operating at millions-of-riders scale.',copy:'Worked across rider and driver products, marketplace optimization, a major TaxiForSure migration and Go Home — balancing customer experience, operational complexity and economics.',type:'ola'},
 {id:'04',tag:'ML / NLP · 2019',name:'Amazon',title:'AI work before the AI boom.',copy:'Built a feature to extract useful keywords from customer reviews, using ML/NLP to turn unstructured feedback into a customer-facing insight.',type:'amazon'}],
 builds:[{label:'Current build · AI',name:'Vireo',copy:'A 0→1 AI personal-assistant MVP, independently conceptualized and shipped.',type:'vireo',link:'https://sabbisurendra-dev.github.io/vireo_ai/',linkText:'View live project ↗'},{label:'Side project · Game',name:'Primal',copy:'A small game built hands-on — another example of turning an idea into a working artifact.',type:'primal',link:'https://sabbisurendra-dev.github.io/primal_game/',linkText:'Play the project ↗'}],
 principles:[['01','Start with the problem.','Clarify the user, business and constraint before jumping to solutions.'],['02','Make complex simple.','Translate systems and ambiguity into experiences people can actually use.'],['03','Use data to reduce uncertainty.','Bring analytics into decisions without letting metrics replace judgment.'],['04','Ship, learn, iterate.','Bias toward tangible releases and fast feedback loops.']],
 timeline:[['2014–18','Analytics → Ola','Data, marketplace & scale'],['2018–20','IIM Calcutta','MBA · Product transition'],['2020–21','Amazon → WorkIndia','ML/NLP · Growth'],['2021–25','Kuhoo','First PM · 0→1 fintech'],['2025–now','AI & Independent Builds','Vireo · rapid prototyping']],
 skills:[['Product','Product strategy · Roadmaps · 0→1 · Product discovery · PRDs · Prioritization · Experimentation · Launches · Stakeholder management'],['Growth & Business','Monetization · Retention · Cohort analysis · Marketplace dynamics · Unit economics · Growth loops · Communication strategy'],['Data','SQL · Analytics · Data manipulation · Metrics · A/B testing · Decision frameworks'],['AI & Technology','Generative AI · Prompt engineering · Ollama · AI prototypes · HTML/CSS · JavaScript · Git/GitHub · Replit']],
 tools:['Gemini','Claude','ChatGPT','Replit','Ollama','Prompt engineering','AI prototyping','HTML / CSS / JS','SQL','Git / GitHub']
};
